var sourcesIndex = JSON.parse('{\
"allocator":["",[],["bitmap.rs","buddy.rs","lib.rs","slab.rs"]],\
"arm_gic":["",[],["gic_v2.rs","lib.rs"]],\
"axalloc":["",[],["lib.rs","page.rs"]],\
"axconfig":["",[],["config_pc_x86.rs","lib.rs"]],\
"axdisplay":["",[],["lib.rs"]],\
"axdriver":["",[["bus",[],["mod.rs","pci.rs"]],["structs",[],["dyn.rs","mod.rs"]]],["drivers.rs","dummy.rs","lib.rs","macros.rs","prelude.rs","virtio.rs"]],\
"axerrno":["",[],["lib.rs"]],\
"axfs":["",[["api",[],["dir.rs","file.rs","mod.rs"]],["fs",[],["mod.rs","myfs.rs"]]],["dev.rs","fops.rs","lib.rs","root.rs"]],\
"axfs_devfs":["",[],["dir.rs","lib.rs","null.rs","zero.rs"]],\
"axfs_ramfs":["",[],["dir.rs","file.rs","lib.rs"]],\
"axfs_vfs":["",[],["lib.rs","macros.rs","path.rs","structs.rs"]],\
"axhal":["",[["arch",[["x86_64",[],["context.rs","gdt.rs","idt.rs","mod.rs"]]],["mod.rs"]],["platform",[["pc_x86",[],["apic.rs","boot.rs","dtables.rs","mem.rs","misc.rs","mod.rs","mp.rs","time.rs","uart16550.rs"]]],["mod.rs"]]],["cpu.rs","irq.rs","lib.rs","mem.rs","paging.rs","time.rs","trap.rs"]],\
"axio":["",[["buffered",[],["bufreader.rs","mod.rs"]]],["error.rs","impls.rs","lib.rs","prelude.rs"]],\
"axlog":["",[],["lib.rs"]],\
"axnet":["",[["smoltcp_impl",[],["dns.rs","listen_table.rs","mod.rs","tcp.rs","udp.rs"]]],["lib.rs"]],\
"axruntime":["",[],["lib.rs","mp.rs","trap.rs"]],\
"axsync":["",[],["lib.rs","mutex.rs"]],\
"axtask":["",[],["api.rs","lib.rs","run_queue.rs","task.rs","timers.rs","wait_queue.rs"]],\
"capability":["",[],["lib.rs"]],\
"crate_interface":["",[],["lib.rs"]],\
"driver_block":["",[],["lib.rs","ramdisk.rs"]],\
"driver_common":["",[],["lib.rs"]],\
"driver_display":["",[],["lib.rs"]],\
"driver_net":["",[],["lib.rs","net_buf.rs"]],\
"driver_pci":["",[],["lib.rs"]],\
"driver_virtio":["",[],["blk.rs","gpu.rs","lib.rs","net.rs"]],\
"flatten_objects":["",[],["lib.rs"]],\
"handler_table":["",[],["lib.rs"]],\
"kernel_guard":["",[["arch",[],["mod.rs","x86.rs"]]],["lib.rs"]],\
"lazy_init":["",[],["lib.rs"]],\
"libax":["",[["cbindings",[],["ctypes_gen.rs","errno.rs","fd_ops.rs","file.rs","malloc.rs","mod.rs","pipe.rs","setjmp.rs","socket.rs","stdio.rs","sys.rs","thread.rs","time.rs","utils.rs"]],["display",[],["mod.rs"]],["io",[],["mod.rs","stdio.rs"]],["net",[],["mod.rs","socket_addr.rs","tcp.rs","udp.rs"]],["sync",[],["mod.rs"]],["thread",[],["mod.rs"]]],["env.rs","fs.rs","lib.rs","rand.rs","time.rs"]],\
"linked_list":["",[],["lib.rs","linked_list.rs","unsafe_list.rs"]],\
"memory_addr":["",[],["lib.rs"]],\
"page_table":["",[["arch",[],["aarch64.rs","mod.rs","riscv.rs","x86_64.rs"]]],["bits64.rs","lib.rs"]],\
"page_table_entry":["",[["arch",[],["aarch64.rs","mod.rs","riscv.rs","x86_64.rs"]]],["lib.rs"]],\
"percpu":["",[],["imp.rs","lib.rs"]],\
"percpu_macros":["",[],["lib.rs","naive.rs"]],\
"ratio":["",[],["lib.rs"]],\
"scheduler":["",[],["cfs.rs","fifo.rs","lib.rs","round_robin.rs"]],\
"slab_allocator":["",[],["lib.rs","slab.rs"]],\
"spinlock":["",[],["base.rs","lib.rs"]],\
"timer_list":["",[],["lib.rs"]],\
"tuple_for_each":["",[],["lib.rs"]]\
}');
createSourceSidebar();
